push:  
    stage: push  
    image: docker:latest  
    services:  
        - docker:dind  
    script:  
        - docker login --username=hesam80 --password=sa13801380
        - docker build -t simpleapp:v0.4  .
        - docker ps
        - docker tag simpleapp:v0.4 hesam80/simpleappss:latest
        - docker push hesam80/simpleappss:latest
  only:  
        - develop

deploy:  
    stage: deploy  
    image: python:3.9  
    variables:  
        COLLECT_ERROR: 1  
    script:  
        - pip install fandogh_cli --upgrade  
        - fandogh login --username $FAN_USR --password $FAN_PASS  
        - ./deployment/scripts/deploy-to-fandogh.sh 
    only:  
  - develop
  
 

# command to run tests
