branches:
  only:
  - dev
language: python
cache: yarn

# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
  - pip install docker

# command to run tests
script:
  - echo $TRAVIS_COMMIT
  - docker login --username=hesam80 --password=sa13801380
  - docker build -t simpleapp:v0.4  .
  - docker ps
  - docker tag simpleapp:v0.4 hesam80/simpleappss:latest
  - docker push hesam80/simpleappss:latest
  
